<?php

namespace AppBundle\Repository;

/**
 * civiliteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class civiliteRepository extends \Doctrine\ORM\EntityRepository
{
}
