<?php

namespace AppBundle\Repository;

/**
 * horaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class horaireRepository extends \Doctrine\ORM\EntityRepository
{
}
